//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenithWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityId { get; set; }
        public string ActivityDescription { get; set; }
        public System.DateTime CreationData { get; set; }
        public int EventId { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
