//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenithWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Activities = new HashSet<Activity>();
            this.Events1 = new HashSet<Event>();
        }
    
        public int EventId { get; set; }
        public System.DateTime EventFromDateAndTime { get; set; }
        public System.DateTime EventToDateAndTime { get; set; }
        public string EnteredByUserName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Event_EventId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events1 { get; set; }
        public virtual Event Event1 { get; set; }
    }
}
